### ISSUE TITLE
Drag playbook to executable

### ISSUE THREAD

**Issue by 4yman-0** [Ameliorated-LLC/trusted-uninstaller-cli#2]
I don't know if this is the right repository to create the issue.

Users should be able to simply drop a playbook on the executable (EXE) and AME will open that playbook.

**Comment by 4yman-el** [comment]
Sorry this repo is not right

**Comment by TheOnlyChuon** [comment]
Doesn't AME Wizard already have this feature?

**Comment by 4yman-0** [comment]
If I recall correctly, it did not work on Windows 10.
